const mensNikeShoes = [
  {
    id: 0,
    name: "Nike Air Max 90",
    variant: "White",
    price: 111.99,
    description: "Stylish Nike Air Max 90 in White",
    image1: "../assets/high1.jpg",
    image2: "nike-air-max-90-red-variant2.jpg",
    image3: "nike-air-max-90-red-variant3.jpg",
    image4: "nike-air-max-90-red-variant4.jpg",
    image5: "nike-air-max-90-red-variant5.jpg",
    colorTheme: ["#B4B2BB", "#232325"],
    inStock: true,
  },
  {
    id: 1,
    name: "Nike Air Max 90",
    variant: "Red",
    price: 129.99,
    description: "Classic Nike Air Max 90 in Red",
    image1: "../assets/high2.jpg",
    image2: "nike-air-max-90-black-variant2.jpg",
    image3: "nike-air-max-90-black-variant3.jpg",
    image4: "nike-air-max-90-black-variant4.jpg",
    image5: "nike-air-max-90-black-variant5.jpg",
    colorTheme: ["#74000B", "#D1B526"],
    inStock: true,
  },
  {
    id: 2,
    name: "Nike Air Max 90",
    variant: "Black",
    price: 139.99,
    description: "Sporty Nike Air Max 90 in Black",
    image1: "../assets/high3.jpg",
    image2: "nike-air-max-90-blue-variant2.jpg",
    image3: "nike-air-max-90-blue-variant3.jpg",
    image4: "nike-air-max-90-blue-variant4.jpg",
    image5: "nike-air-max-90-blue-variant5.jpg",
    colorTheme: ["#000000", "#764F3D"],
    inStock: true,
  },
  {
    id: 3,
    name: "Nike Air Max 90",
    variant: "Blue",
    price: 139.99,
    description: "Sporty Nike Air Max 90 in Blue",
    image1: "../assets/high4.jpg",
    image2: "nike-air-max-90-blue-variant2.jpg",
    image3: "nike-air-max-90-blue-variant3.jpg",
    image4: "nike-air-max-90-blue-variant4.jpg",
    image5: "nike-air-max-90-blue-variant5.jpg",
    colorTheme: ["#96A4BF", "#1F266A"],
    inStock: false, // Set to false for the last one
  },
  // Add more shoe variants with unique IDs
];
